name: Cpp

on:
  push:
    branches:
      - master
    paths:
      - 'cpp/**'
  pull_request:
    branches:
      - '*'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup build dir
        run: mkdir ${{ github.workspace }}/cpp/build

      - name: CMake configure release
        working-directory: ${{ github.workspace }}/cpp/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: CMake build
        working-directory: ${{ github.workspace }}/cpp/build
        run: cmake --build .
